// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type Product struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	PriceInCent int32  `json:"price_in_cent"`
	Quantity    int32  `json:"quantity"`
}
