// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repo

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name, price_in_cent, quantity FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCent,
		&i.Quantity,
	)
	return i, err
}

const getProductsList = `-- name: GetProductsList :many
SELECT id, name, price_in_cent, quantity FROM products
`

func (q *Queries) GetProductsList(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCent,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
